image: nberlette/gitpod-enhanced

tasks:
- init: | 
    export DENO_INSTALL="/home/gitpod/.deno" PATH="$DENO_INSTALL/bin:$PATH"
    curl -fsSL https://deno.land/install.sh | sh -

vscode:
  extensions:
    - "denoland.vscode-deno"
    - "editorconfig.editorconfig"
    - "vsls-contrib.gistfs"
    - "sdras.night-owl"
    - "redhat.vscode-yaml"
    - "antfu.iconify"
    - "antfu.browse-lite"
    - "bierner.markdown-preview-github-styles"
    - "gitpod.gitpod-desktop"
    - "gitpod.gitpod-remote-ssh"

github:
  prebuilds:
    branches: true
    pullRequestsFromForks: true
    addLabel: "gitpod-prebuilt"
    addCheck: "prevent-merge-on-error"
    addBadge: true
