name: "🦕 Deno CI"
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  deno:
    runs-on: ${{matrix.os}}
    # Continue in case the canary run does not succeed
    continue-on-error: ${{matrix.canary}}
    strategy:
      matrix:
        os: [ ubuntu-20.04 ]
        deno: [ v1.x ]
        canary: [ false ]
        include:
          - deno: canary
            os: ubuntu-20.04
            canary: true
    steps:
      - name: "(env) gitconfig"
        run: |
          sudo git config --system core.autocrlf false
          sudo git config --system core.eol lf

      - name: "(env) checkout"
        uses: actions/checkout@v3

      - name: "(setup) 🦕 ${{matrix.deno}}"
        uses: denoland/setup-deno@main
        with:
          deno-version: ${{matrix.deno}}

      - name: "(run) fmt --check"
        run: deno fmt --check

      - name: "(run) lint"
        run: deno lint --unstable
